//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Model {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Model() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kino.Web.App_GlobalResources.Model", typeof(Model).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string LogOn_Password {
            get {
                return ResourceManager.GetString("LogOn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL.
        /// </summary>
        public static string LogOn_Pesel {
            get {
                return ResourceManager.GetString("LogOn_Pesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowa forma PESELu.
        /// </summary>
        public static string LogOn_PeselRestriction {
            get {
                return ResourceManager.GetString("LogOn_PeselRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie?.
        /// </summary>
        public static string LogOn_RememberMe {
            get {
                return ResourceManager.GetString("LogOn_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole {0} jest wymagane.
        /// </summary>
        public static string LogOn_Requirence {
            get {
                return ResourceManager.GetString("LogOn_Requirence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Registration_Address {
            get {
                return ResourceManager.GetString("Registration_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        public static string Registration_City {
            get {
                return ResourceManager.GetString("Registration_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        public static string Registration_ConfirmPassword {
            get {
                return ResourceManager.GetString("Registration_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Registration_Email {
            get {
                return ResourceManager.GetString("Registration_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string Registration_Name {
            get {
                return ResourceManager.GetString("Registration_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Registration_Password {
            get {
                return ResourceManager.GetString("Registration_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło oraz powtórzone hasło nie zgadzają się ze sobą..
        /// </summary>
        public static string Registration_PasswordMatching {
            get {
                return ResourceManager.GetString("Registration_PasswordMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} musi mieć minimum {2} znaki..
        /// </summary>
        public static string Registration_PasswordRestriction {
            get {
                return ResourceManager.GetString("Registration_PasswordRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL.
        /// </summary>
        public static string Registration_PESEL {
            get {
                return ResourceManager.GetString("Registration_PESEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowa forma PESELu.
        /// </summary>
        public static string Registration_PeselRestriction {
            get {
                return ResourceManager.GetString("Registration_PeselRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Registration_Phone {
            get {
                return ResourceManager.GetString("Registration_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer jest za długi.
        /// </summary>
        public static string Registration_PhoneToLong {
            get {
                return ResourceManager.GetString("Registration_PhoneToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Pocztowy.
        /// </summary>
        public static string Registration_Postcode {
            get {
                return ResourceManager.GetString("Registration_Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy kod pocztowy.
        /// </summary>
        public static string Registration_PostcodeRestriction {
            get {
                return ResourceManager.GetString("Registration_PostcodeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole {0} jest wymagane.
        /// </summary>
        public static string Registration_Requirence {
            get {
                return ResourceManager.GetString("Registration_Requirence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string Registration_Surname {
            get {
                return ResourceManager.GetString("Registration_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string User_Address {
            get {
                return ResourceManager.GetString("User_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia.
        /// </summary>
        public static string User_CreationDate {
            get {
                return ResourceManager.GetString("User_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język.
        /// </summary>
        public static string User_Culture {
            get {
                return ResourceManager.GetString("User_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnie aktywność.
        /// </summary>
        public static string User_LastActivity {
            get {
                return ResourceManager.GetString("User_LastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię i Nazwisko.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL.
        /// </summary>
        public static string User_PESEL {
            get {
                return ResourceManager.GetString("User_PESEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string User_Phone {
            get {
                return ResourceManager.GetString("User_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punktów.
        /// </summary>
        public static string User_Points {
            get {
                return ResourceManager.GetString("User_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość Rezerwacji.
        /// </summary>
        public static string User_ReservationCnt {
            get {
                return ResourceManager.GetString("User_ReservationCnt", resourceCulture);
            }
        }
    }
}
