//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class View {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal View() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kino.Web.App_GlobalResources.View", typeof(View).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        public static string Account_ChangePassword_Ok {
            get {
                return ResourceManager.GetString("Account_ChangePassword_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Filmów.
        /// </summary>
        public static string Admin_FilmsList {
            get {
                return ResourceManager.GetString("Admin_FilmsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Administracyjny.
        /// </summary>
        public static string Admin_Panel {
            get {
                return ResourceManager.GetString("Admin_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Sal.
        /// </summary>
        public static string Admin_RoomsList {
            get {
                return ResourceManager.GetString("Admin_RoomsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Użytkowników.
        /// </summary>
        public static string Admin_UsersList {
            get {
                return ResourceManager.GetString("Admin_UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Administracyjny.
        /// </summary>
        public static string Log_AdminPanel {
            get {
                return ResourceManager.GetString("Log_AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string Log_Out {
            get {
                return ResourceManager.GetString("Log_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalogowany jako.
        /// </summary>
        public static string Logged_User {
            get {
                return ResourceManager.GetString("Logged_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje o koncie.
        /// </summary>
        public static string LogOn_AccountInfo {
            get {
                return ResourceManager.GetString("LogOn_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie nieudane. Popraw błędy i spróbuj ponownie..
        /// </summary>
        public static string LogOn_Error {
            get {
                return ResourceManager.GetString("LogOn_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałem hasła.
        /// </summary>
        public static string LogOn_ForgottenPassLabel {
            get {
                return ResourceManager.GetString("LogOn_ForgottenPassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string LogOn_MainLabel {
            get {
                return ResourceManager.GetString("LogOn_MainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zarejestruj się.
        /// </summary>
        public static string LogOn_RegisterLabel {
            get {
                return ResourceManager.GetString("LogOn_RegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poniżej wpisz swój nick oraz hasło, lub.
        /// </summary>
        public static string LogOn_TooltipPart1 {
            get {
                return ResourceManager.GetString("LogOn_TooltipPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jeśli jeszcze nie masz konta..
        /// </summary>
        public static string LogOn_TooltipPart2 {
            get {
                return ResourceManager.GetString("LogOn_TooltipPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepraszamy, wystąpił nieoczekiwany błąd podczas przetwarzania zapytania..
        /// </summary>
        public static string Main_Error {
            get {
                return ResourceManager.GetString("Main_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string Main_ErrorTitle {
            get {
                return ResourceManager.GetString("Main_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj na stronie kina &quot;Widz&quot;..
        /// </summary>
        public static string Main_Hello {
            get {
                return ResourceManager.GetString("Main_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapraszamy na nasze filmy!.
        /// </summary>
        public static string Main_Invitation {
            get {
                return ResourceManager.GetString("Main_Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Master_Contact {
            get {
                return ResourceManager.GetString("Master_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filmy.
        /// </summary>
        public static string Master_Films {
            get {
                return ResourceManager.GetString("Master_Films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2013 Strona stworzona na Laboratoria PO.
        /// </summary>
        public static string Master_Footer {
            get {
                return ResourceManager.GetString("Master_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona Główna.
        /// </summary>
        public static string Master_MainSite {
            get {
                return ResourceManager.GetString("Master_MainSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promocje.
        /// </summary>
        public static string Master_Promotion {
            get {
                return ResourceManager.GetString("Master_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertuar.
        /// </summary>
        public static string Master_Repertoire {
            get {
                return ResourceManager.GetString("Master_Repertoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje o koncie.
        /// </summary>
        public static string Register_AccountInfo {
            get {
                return ResourceManager.GetString("Register_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść.
        /// </summary>
        public static string Register_ClearButton {
            get {
                return ResourceManager.GetString("Register_ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postwierdzenie rejestracji.
        /// </summary>
        public static string Register_ConfirmationLabel {
            get {
                return ResourceManager.GetString("Register_ConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proces rejestracji przebiegł pomyślnie..
        /// </summary>
        public static string Register_ConfirmationPart1 {
            get {
                return ResourceManager.GetString("Register_ConfirmationPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdź swój email - został na niego wysłany link aktywacyjny.
        /// </summary>
        public static string Register_ConfirmationPart2 {
            get {
                return ResourceManager.GetString("Register_ConfirmationPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz nowe konto.
        /// </summary>
        public static string Register_CreateNewAccount {
            get {
                return ResourceManager.GetString("Register_CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użyj poniższego formularza do utworzenia nowego konta.
        /// </summary>
        public static string Register_FormHelpTip {
            get {
                return ResourceManager.GetString("Register_FormHelpTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło musi mieć minimum.
        /// </summary>
        public static string Register_MinPasswordChar_Part1 {
            get {
                return ResourceManager.GetString("Register_MinPasswordChar_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to znaki..
        /// </summary>
        public static string Register_MinPasswordChar_Part2 {
            get {
                return ResourceManager.GetString("Register_MinPasswordChar_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestruj.
        /// </summary>
        public static string Register_RegButton {
            get {
                return ResourceManager.GetString("Register_RegButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie konta zakończone niepowodzeniem. Popraw błędy i spróbuj jeszcze raz..
        /// </summary>
        public static string Register_RegistrationError {
            get {
                return ResourceManager.GetString("Register_RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * obowiązkowe.
        /// </summary>
        public static string Register_RequiredFields {
            get {
                return ResourceManager.GetString("Register_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz datę.
        /// </summary>
        public static string Repertoire_ChooseDate {
            get {
                return ResourceManager.GetString("Repertoire_ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz datę.
        /// </summary>
        public static string Repertoire_Date {
            get {
                return ResourceManager.GetString("Repertoire_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repertuar.
        /// </summary>
        public static string Repertoire_MainLabel {
            get {
                return ResourceManager.GetString("Repertoire_MainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezerwacja udana.
        /// </summary>
        public static string Repertoire_ReservationSuccess {
            get {
                return ResourceManager.GetString("Repertoire_ReservationSuccess", resourceCulture);
            }
        }
    }
}
